### ISSUE TITLE
Removeable chip icon placement

### ISSUE THREAD

**Issue by cooper-joe** [dhis2/ui-core#418] opened 2019-09-11 12:28 UTC
The 'remove' icon placement is not vertically centered in Firefox. Ideally needs to move down a pixel (maybe two). The centering is better in Chrome. 

Firefox screengrab:
![image](https://user-images.githubusercontent.com/33054985/64697092-58222780-d4a0-11e9-9707-bddabd2ceb8f.png)

**Comment by HendrikThePendric** [comment] 2019-10-15 09:00
@cooper-joe I can't reproduce this problem, see a FF screenshot from my Mac below:
<img width="124" alt="Screenshot 2019-10-15 at 10 58 10" src="https://user-images.githubusercontent.com/353236/66816723-d5770700-ef3a-11e9-874f-763a5e4ff4c7.png">
Could you double-check, and if the problem is not there anymore, please close this issue?

**Comment by Mohammer5** [comment] 2019-10-15 09:05
I can reproduce it and figured out the issue (the span surrounding the svg needs to be display block and the margin-right needs to be moved up from the svg to the span).

I'll prepare a PR

**Comment by HendrikThePendric** [comment] 2019-11-05 12:23
Resolved in #512

**Closed by HendrikThePendric** 2019-11-05 12:23 UTC
Labels: bug
